<a href="https://colab.research.google.com/github/nikhilg99/Bharat_BA_Task1/blob/main/bharat_intern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sales/train.csv')
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sales/test.csv')

In [ ]:
df_train

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08-11-2017  11-11-2017    Second Class   
1          2  CA-2017-152156  08-11-2017  11-11-2017    Second Class   
2          3  CA-2017-138688  12-06-2017  16-06-2017    Second Class   
3          4  US-2016-108966  11-10-2016  18-10-2016  Standard Class   
4          5  US-2016-108966  11-10-2016  18-10-2016  Standard Class   
...      ...             ...         ...         ...             ...   
6994    6995  CA-2016-109386  08-11-2016  13-11-2016    Second Class   
6995    6996  CA-2016-166800  19-11-2016  26-11-2016  Standard Class   
6996    6997  CA-2018-117443  23-12-2018  25-12-2018    Second Class   
6997    6998  CA-2018-117443  23-12-2018  25-12-2018    Second Class   
6998    6999  US-2017-134369  16-09-2017  22-09-2017  Standard Class   

     Customer ID        Customer Name      Segment        Country  \
0       CG-12520          Claire Gute     Consumer  United States   
1       CG-12520          Claire Gute     Consumer  United States   
2       DV-13045      Darrin Van Huff    Corporate  United States   
3       SO-20335       Sean O'Donnell     Consumer  United States   
4       SO-20335       Sean O'Donnell     Consumer  United States   
...          ...                  ...          ...            ...   
6994    RH-19600         Rob Haberlin     Consumer  United States   
6995    AG-10300  Aleksandra Gannaway    Corporate  United States   
6996    JB-15400     Jennifer Braxton    Corporate  United States   
6997    JB-15400     Jennifer Braxton    Corporate  United States   
6998    BC-11125        Becky Castell  Home Office  United States   

                 City       State  Postal Code   Region       Product ID  \
0           Henderson    Kentucky      42420.0    South  FUR-BO-10001798   
1           Henderson    Kentucky      42420.0    South  FUR-CH-10000454   
2         Los Angeles  California      90036.0     West  OFF-LA-10000240   
3     Fort Lauderdale     Florida      33311.0    South  FUR-TA-10000577   
4     Fort Lauderdale     Florida      33311.0    South  OFF-ST-10000760   
...               ...         ...          ...      ...              ...   
6994          Hampton    Virginia      23666.0    South  OFF-AR-10000122   
6995        Las Vegas      Nevada      89115.0     West  OFF-AP-10004868   
6996         Rockford    Illinois      61107.0  Central  OFF-BI-10004002   
6997         Rockford    Illinois      61107.0  Central  OFF-PA-10004475   
6998    Laguna Niguel  California      92677.0     West  OFF-PA-10002195   

             Category Sub-Category  \
0           Furniture    Bookcases   
1           Furniture       Chairs   
2     Office Supplies       Labels   
3           Furniture       Tables   
4     Office Supplies      Storage   
...               ...          ...   
6994  Office Supplies          Art   
6995  Office Supplies   Appliances   
6996  Office Supplies      Binders   
6997  Office Supplies        Paper   
6998  Office Supplies        Paper   

                                           Product Name     Sales  
0                     Bush Somerset Collection Bookcase  261.9600  
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2     Self-Adhesive Address Labels for Typewriters b...   14.6200  
3         Bretford CR4500 Series Slim Rectangular Table  957.5775  
4                        Eldon Fold 'N Roll Cart System   22.3680  
...                                                 ...       ...  
6994                                         Newell 314   27.9000  
6995  Hoover Commercial Soft Guard Upright Vacuum An...   31.0800  
6996    Wilson Jones International Size A4 Ring Binders   13.8400  
6997                                         Xerox 1940  175.8720  
6998                                         Xerox 1966   12.9600  

[6999 rows x 18 columns]

In [ ]:
df_train.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      2
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [ ]:
df_test.isnull().sum()

Row ID              0
Order ID            0
Order Date          0
Ship Date           0
Ship Mode           0
Customer ID         0
Customer Name       0
Segment             0
Country             0
City                0
State               0
Postal Code         9
Region              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales            2801
dtype: int64

In [ ]:
#No null values

In [ ]:
#dropping coloumns which are not required
df_train.drop(['Row ID','Order ID','Ship Date','Ship Mode','Country','Customer ID','Customer Name'],axis=1,inplace=True)
df_test.drop(['Row ID','Order ID','Ship Date','Ship Mode','Country','Customer ID','Customer Name'],axis=1,inplace=True)

In [ ]:
df_train.head(5)

Order Date    Segment             City       State  Postal Code Region  \
0  08-11-2017   Consumer        Henderson    Kentucky      42420.0  South   
1  08-11-2017   Consumer        Henderson    Kentucky      42420.0  South   
2  12-06-2017  Corporate      Los Angeles  California      90036.0   West   
3  11-10-2016   Consumer  Fort Lauderdale     Florida      33311.0  South   
4  11-10-2016   Consumer  Fort Lauderdale     Florida      33311.0  South   

        Product ID         Category Sub-Category  \
0  FUR-BO-10001798        Furniture    Bookcases   
1  FUR-CH-10000454        Furniture       Chairs   
2  OFF-LA-10000240  Office Supplies       Labels   
3  FUR-TA-10000577        Furniture       Tables   
4  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  
0                  Bush Somerset Collection Bookcase  261.9600  
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400  
2  Self-Adhesive Address Labels for Typewriters b...   14.6200  
3      Bretford CR4500 Series Slim Rectangular Table  957.5775  
4                     Eldon Fold 'N Roll Cart System   22.3680

In [ ]:
!pip install pandas
!pip install pandas-profiling

# EDA usind Pandas Profiling

In [ ]:
from pandas_profiling import ProfileReport

<ipython-input-13-e2a33329b6f0>:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [ ]:
profile = ProfileReport(df_train, title = "Pandas Profiling Report")
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Preprocessing
### 1. Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df_train['Segment'] = le.fit_transform(df_train['Segment'])
df_train['City'] = le.fit_transform(df_train['City'])
df_train['State'] = le.fit_transform(df_train['State'])
df_train['Region'] = le.fit_transform(df_train['Region'])
df_train['Category'] = le.fit_transform(df_train['Category'])
df_train['Sub-Category'] = le.fit_transform(df_train['Sub-Category'])
df_train['Product Name'] = le.fit_transform(df_train['Product Name'])
df_train['Postal Code'] = le.fit_transform(df_train['Postal Code'])
df_train['Order Date'] = le.fit_transform(df_train['Order Date'])
df_train['Product ID'] = le.fit_transform(df_train['Product ID'])


In [ ]:
df_train

Order Date  Segment  City  State  Postal Code  Region  Product ID  \
0            297        0   176     15          201       2          11   
1            297        0   176     15          201       2          54   
2            420        1   243      3          478       3         927   
3            399        0   138      8          155       2         311   
4            399        0   138      8          155       2        1287   
...          ...      ...   ...    ...          ...     ...         ...   
6994         296        0   170     44           96       2         463   
6995         698        1   225     26          472       3         460   
6996         862        1   381     11          323       0         784   
6997         862        1   381     11          323       0        1239   
6998         581        2   214      3          518       3        1128   

      Category  Sub-Category  Product Name     Sales  
0            0             4           378  261.9600  
1            0             5           819  731.9400  
2            1            10          1399   14.6200  
3            0            16           359  957.5775  
4            1            14           562   22.3680  
...        ...           ...           ...       ...  
6994         1             2          1093   27.9000  
6995         1             1           844   31.0800  
6996         1             3          1593   13.8400  
6997         1            12          1683  175.8720  
6998         1            12          1709   12.9600  

[6999 rows x 11 columns]

# Splitting data into train and test

In [ ]:
X = df_train.drop('Sales',axis=1)
Y = df_train['Sales']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=101, test_size=0.2)

In [ ]:
X.describe()

Order Date      Segment         City        State  Postal Code  \
count  6999.000000  6999.000000  6999.000000  6999.000000  6999.000000   
mean    560.079440     0.651379   257.759680    22.060437   287.907987   
std     325.857075     0.764249   127.854465    15.437793   185.566044   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%     286.000000     0.000000   152.000000     4.000000    91.000000   
50%     551.000000     0.000000   269.000000    24.000000   290.000000   
75%     837.000000     1.000000   365.500000    36.000000   476.000000   
max    1142.000000     2.000000   488.000000    47.000000   582.000000   

            Region   Product ID     Category  Sub-Category  Product Name  
count  6999.000000  6999.000000  6999.000000   6999.000000   6999.000000  
mean      1.578368   881.325189     0.974854      7.640234    895.239463  
std       1.163337   512.829771     0.627508      5.032250    518.578182  
min       0.000000     0.000000     0.000000      0.000000      0.000000  
25%       1.000000   453.000000     1.000000      3.000000    456.000000  
50%       1.000000   853.000000     1.000000      9.000000    884.000000  
75%       3.000000  1319.500000     1.000000     12.000000   1350.000000  
max       3.000000  1809.000000     2.000000     16.000000   1799.000000

# Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [ ]:
X_train_std= sc.fit_transform(X_train)
X_test_std= sc.transform(X_test)

In [ ]:
X_train_std

array([[ 0.7734121 , -0.85228119,  1.21400348, ...,  0.02928693,
         0.86402826,  1.6047491 ],
       [ 1.56495379,  0.45223559,  0.66667661, ...,  0.02928693,
         1.26199586,  1.18995063],
       [ 1.48211803, -0.85228119,  1.12799497, ...,  0.02928693,
        -1.32479357, -1.63453757],
       ...,
       [ 0.41445715,  0.45223559,  0.66667661, ...,  0.02928693,
         0.86402826,  0.02079773],
       [ 0.90533572,  0.45223559,  1.10453811, ...,  0.02928693,
        -0.92682597, -0.39978863],
       [ 0.31014545,  1.75675237, -0.12303787, ...,  1.62130149,
         1.06301206, -0.26280867]])

# Model

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()

In [ ]:
lr.fit(X_train_std,Y_train)

LinearRegression()

In [ ]:
Y_pred_lr=lr.predict(X_test_std)
Y_pred_lr

array([341.54294175, 231.2608935 , 252.83328729, ..., 169.51085829,
       265.25177182, 221.45012535])

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
print(r2_score(Y_test,Y_pred_lr))
print(mean_absolute_error(Y_test,Y_pred_lr))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_lr)))

0.017652960835668807
263.97933125545825
509.89616309892796


In [ ]:
# Very low correlation (r2_score is less than 0.2)

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(n_estimators=1000)

In [ ]:
rf.fit(X_train_std,Y_train)

RandomForestRegressor(n_estimators=1000)

In [ ]:
Y_pred_rf= rf.predict(X_test_std)
Y_pred_rf

array([155.759879,  31.871632,  20.443379, ...,  41.123464, 166.976556,
        38.468255])

In [ ]:
print(r2_score(Y_test,Y_pred_rf))
print(mean_absolute_error(Y_test,Y_pred_rf))
print(np.sqrt(mean_squared_error(Y_test,Y_pred_rf)))

0.4315311445330894
161.15077611538092
387.8846664702698


In [ ]:
#Random Forest performed better than linear regression